"""add vbat and uptime to measurement

Revision ID: 16d8a275e181
Revises: 18a35818c1fd
Create Date: 2026-08-23 10:12:04.826813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d8a275e181'
down_revision: Union[str, Sequence[str], None] = '18a35818c1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('vbat', sa.Float(), nullable=True))
    op.add_column('measurement', sa.Column('uptime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement', 'uptime')
    op.drop_column('measurement', 'vbat')
    # ### end Alembic commands ###
