"""add rssi and snr to measurement

Revision ID: 331337b1c112
Revises: 03acac602dee
Create Date: 2026-07-26 13:57:58.389465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '331337b1c112'
down_revision: Union[str, Sequence[str], None] = '03acac602dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('rssi', sa.Integer(), nullable=True))
    op.add_column('measurement', sa.Column('snr', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement', 'snr')
    op.drop_column('measurement', 'rssi')
    # ### end Alembic commands ###
