"""add soil_raw to measurement

Revision ID: afea071620cb
Revises: 16d8a275e181
Create Date: 2026-08-24 10:59:39.684711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afea071620cb'
down_revision: Union[str, Sequence[str], None] = '16d8a275e181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('soil_raw', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement', 'soil_raw')
    # ### end Alembic commands ###
